apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "nais-logd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nais-logd.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "events"]
    verbs: ["get", "watch", "list"]
{{- if .Values.psp.use }}
  - apiGroups:
    - policy
    resourceNames:
    - {{ .Values.psp.name }}
    resources:
    - podsecuritypolicies
    verbs:
    - use
{{- end }}
