apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "nais-logd.fluentd.fullname" . }}
  labels:
    app: {{ template "nais-logd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.fluentd.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "nais-logd.name" . }}
        component: "{{ .Values.fluentd.name }}"
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ template "nais-logd.fullname" . }}
      containers:
      - name: {{ template "nais-logd.name" . }}-{{ .Values.fluentd.name }}
        image: "{{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}"
        imagePullPolicy: "{{ .Values.fluentd.image.pullPolicy }}"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "{{ .Values.elasticsearch.hosts }}"
          - name: ELASTICSEARCH_INDEX_PREFIX
            value: "{{ .Values.elasticsearch.index_prefix }}"
          - name: CLUSTER_NAME
            value: "{{ .Values.cluster.name }}"
          - name: CLUSTER_ENVCLASS
            value: "{{ .Values.cluster.envclass }}"
        ports:
          - name: metrics
            containerPort: 9000
            protocol: TCP
        volumeMounts:
{{- if .Values.configFiles }}
          - name: config-volume
            mountPath: /fluentd/etc
{{- end }}
{{- range $volume := .Values.volumes }}
          - name: "{{ $volume.name }}"
            mountPath: "{{ $volume.mountPath }}"
            readOnly: {{ $volume.readOnly }}
{{- end }}
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists
      volumes:
{{- if .Values.configFiles }}
        - name: config-volume
          configMap:
            name: {{ template "nais-logd.fullname" . }}
{{- end }}
{{- range $volume := .Values.volumes }}
        - name: "{{ $volume.name }}"
          hostPath:
            path: "{{ $volume.hostPath }}"
{{- end }}
