apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "nais-logd.fluentd.fullname" . }}
  labels:
    app: {{ template "nais-logd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.fluentd.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "nais-logd.name" . }}
        component: "{{ .Values.fluentd.name }}"
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "nais-logd.fullname" . }}
      containers:
      - name: {{ template "nais-logd.name" . }}-{{ .Values.fluentd.name }}
        image: "{{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}"
        imagePullPolicy: "{{ .Values.fluentd.image.pullPolicy }}"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "{{ .Values.elasticsearch.hosts }}"
          - name: ELASTICSEARCH_INDEX_PREFIX
            value: "{{ .Values.elasticsearch.index_prefix }}"
          - name: CLUSTER_NAME
            value: "{{ .Values.cluster.name }}"
          - name: CLUSTER_ENVCLASS
            value: "{{ .Values.cluster.envclass }}"
        volumeMounts:
{{- if .Values.configFiles }}
          - name: config-volume
            mountPath: /fluentd/etc
{{- end }}
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists
      volumes:
{{- if .Values.configFiles }}
        - name: config-volume
          configMap:
            name: {{ template "nais-logd.fullname" . }}
{{- end }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
