apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "nais-logd.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "nais-logd.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "nais-logd.fullname" . }}
      nodeSelector:
        nais.io/type: worker
      containers:
      - name: {{ template "nais-logd.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: ELASTICSEARCH_HOST
            value: "{{ .Values.elasticsearch.host }}"
          - name: ELASTICSEARCH_PORT
            value: "{{ .Values.elasticsearch.port }}"
          - name: ELASTICSEARCH_INDEX_PREFIX
            value: "{{ .Values.elasticsearch.index_prefix }}"
          - name: CLUSTER_NAME
            value: "{{ .Values.cluster.name }}"
          - name: CLUSTER_ENVCLASS
            value: "{{ .Values.cluster.envclass }}"
        volumeMounts:
{{- if .Values.configFiles }}
          - name: config-volume
            mountPath: /fluentd/etc
{{- end }}
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
{{- if .Values.configFiles }}
        - name: config-volume
          configMap:
            name: {{ template "nais-logd.fullname" . }}
{{- end }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
