kind: Endpoints
apiVersion: v1
metadata:
  labels:
    app: {{ template "nais-logd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Values.elasticsearch.host }}"
subsets:
{{- $port := .Values.elasticsearch.port -}}
{{- range $ip := .Values.elasticsearch.ip }}
  - addresses:
      - ip: {{ $ip }}
    ports:
      - port: {{ $port }}
{{- end }}
