{{- if .Values.kubewatch.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nais-logd.kubewatch.fullname" . }}
  labels:
    app: {{ template "nais-logd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.kubewatch.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "nais-logd.name" . }}
      release: {{ .Release.Name }}
      component: "{{ .Values.kubewatch.name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "nais-logd.name" . }}
        component: "{{ .Values.kubewatch.name }}"
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "nais-logd.fullname" . }}
      containers:
      - name: {{ .Values.kubewatch.name }}
        {{- if .Values.kubewatch.image.digest }}
        image: "{{ .Values.kubewatch.image.repository }}@{{ .Values.kubewatch.image.digest }}"
        {{- else }}
        image: "{{ .Values.kubewatch.image.repository }}:{{ .Values.kubewatch.image.tag }}"
        {{- end }}
        imagePullPolicy: "{{ .Values.kubewatch.image.pullPolicy }}"
        args:
          - events
        resources:
{{ toYaml .Values.kubewatch.resources | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["all"]
          readOnlyRootFilesystem: true
          runAsNonRoot: {{ .Values.runAsNonRoot }}
          runAsUser: {{ .Values.runAsUser }}
      terminationGracePeriodSeconds: 30
{{- end }}
