---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nais-logd
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  namespace: kube-system
  name: nais:nais-logd
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: nais:nais-logd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nais:nais-logd
subjects:
- kind: ServiceAccount
  name: nais-logd
  namespace: kube-system
