---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "nais-logd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Values.elasticsearch.host }}"
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
---
kind: Endpoints
apiVersion: v1
metadata:
  labels:
    app: {{ template "nais-logd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Values.elasticsearch.host }}"
  namespace: kube-system
subsets:
{{- $port := .Values.elasticsearch.port -}}
{{- range $ip := .Values.elasticsearch.ip }}
  - addresses:
      - ip: {{ $ip }}
    ports:
      - port: {{ $port }}
{{- end }}
