psp:
  enabled: true
#  Set existingPsp to use a psp already defined in the cluster
#  existingPsp: otherpsp
  allowedHostPaths:
  - pathPrefix: /var/log
  - pathPrefix: /var/log/pods
fluentd:
  name: fluentd
  image:
    repository: docker.pkg.github.com/nais/nais-logd/nais-logd
    tag: 106
#    digest: sha256:9ac13816157d1127f04a9ac262e476903f3b8d3ee2c9aef9a2cee82ac79fd3c2
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  updateStrategy: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
  initContainers: []
  pos_file:
    containers: /var/log/es-containers.log.pos
    journal: /var/log/journald.log.pos
  timezone: UTC
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 384Mi
    # requests:
    #   cpu: 100m
    #   memory: 384Mi
configmapReload:
  image:
    repository: jimmidyson/configmap-reload
    digest: sha256:befec9f23d2a9da86a298d448cc9140f56a457362a7d9eecddba192db1ab489e
  resources:
    requests:
      cpu: 10m
      memory: 10M
    limits:
      cpu: 100m
      memory: 100M
elasticsearch:
  hosts: elasticsearch-logging:9200
  scheme: http
  ssl_verify: true
  ca_file: /etc/pki/tls/certs/ca-bundle.crt
  index_name: logstash-apps-test
  logstash_format: true
  logstash_prefix: logstash-apps-test
  type_name: containerlog
  max_retries: 0
cluster:
  name: kubernetes
  envclass: t
kubewatch:
  enable: true
  name: kubewatch
  image:
    repository: softonic/kubewatch
#    tag: v0.3.3
    digest: sha256:5fb7150eb75339af8259de14ec7438ce6b290bbd6e43425c27dc97263c565e6d
    pullPolicy: IfNotPresent
  resources: {}
    # limits:
    #   cpu: 20m
    #   memory: 32Mi
    # requests:
    #   cpu: 20m
    #   memory: 32Mi
throttle:
  bucket_period: 60
  bucket_limit: 8000
  reset_rate: 100
  drop_logs: true
runAsNonRoot: true
runAsUser: 1065
runAsGroup: 1065
# enabling logs_acl will add a container using file system acls to ensure that logs files are readable by the specified gid
logs_acl:
  enable: true
  gid: 1065
  image: ghcr.io/nais/set-logs-acl:4
  container_log_dir: /var/log/pods
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 100M
    # requests:
    #   cpu: 10m
    #   memory: 20M
volumes:
  - name: varlog
    mountPath: /var/log
    hostPath: /var/log
    readOnly: false
  - name: containerlogdir
    mountPath: /var/log/pods
    hostPath: /var/log/pods
    readOnly: true
# configMaps:
# - name: configmap-name
#   path: mount-path
#  subPath: sub-path
configMaps: []
    
# Add to override conf file in docker image
# configFiles:
#   fluent.conf: |-
#     <match **>
#       @type ...
#     </match>
