server:
  name: nais-logd

image:
  repository: navikt/nais-logd
  tag: 13
elasticsearch:
  host: elasticsearch-logging
  port: 9200
  index_prefix: logstash-apps-test
  # ip addresses to elasticsearch ingest nodes
  ip:
    - 1.2.3.4
cluster:
  name: kubernetes
  envclass: t

# Add to override conf file in docker image
# configFiles:
#   fluent.conf: |-
#      foobar
