image:
  repository: navikt/nais-logd
  tag: 42
elasticsearch:
  hosts: elasticsearch-logging:9200
  index_prefix: logstash-apps-test
cluster:
  name: kubernetes
  envclass: t

# Add to override conf file in docker image
# configFiles:
#   fluent.conf: |-
#     <match **>
#       @type ...
#     </match>
