fluentd:
  name: fluentd
  image:
    repository: navikt/nais-logd
#    tag: 97
    digest: sha256:687693e8715cabd3646b9cb2511dd6ec0f94ca37028dca322c0070b499b023f8
    pullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  pos_file:
    containers: /var/log/es-containers.log.pos
    journal: /var/log/journald.log.pos
  timezone: UTC
elasticsearch:
  hosts: elasticsearch-logging:9200
  scheme: http
  ssl_verify: true
  ca_file: /etc/pki/tls/certs/ca-bundle.crt
  index_name: logstash-apps-test
  logstash_format: true
  logstash_prefix: logstash-apps-test
  type_name: containerlog
  max_retries: 0
cluster:
  name: kubernetes
  envclass: t
kubewatch:
  enable: true
  name: kubewatch
  image:
    repository: softonic/kubewatch
#    tag: v0.3.3
    digest: sha256:5fb7150eb75339af8259de14ec7438ce6b290bbd6e43425c27dc97263c565e6d
    pullPolicy: IfNotPresent
throttle:
  bucket_period: 60
  bucket_limit: 8000
  reset_rate: 100
  drop_logs: true
volumes:
  - name: varlog
    mountPath: /var/log
    hostPath: /var/log
    readOnly: false
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    hostPath: /var/lib/docker/containers
    readOnly: true
# configMaps:
# - name: configmap-name
#   path: mount-path
#  subPath: sub-path
configMaps: []
    
# Add to override conf file in docker image
# configFiles:
#   fluent.conf: |-
#     <match **>
#       @type ...
#     </match>
