fluentd:
  name: fluentd
  image:
    repository: navikt/nais-logd
#    tag: 79
    digest: sha256:dbd49379d61a78d0cfd06f27d4d736a41ebecc148fb5bce11c3fd60204175271
    pullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
elasticsearch:
  hosts: elasticsearch-logging:9200
  index_prefix: logstash-apps-test
cluster:
  name: kubernetes
  envclass: t
kubewatch:
  enable: true
  name: kubewatch
  image:
    repository: softonic/kubewatch
#    tag: v0.3.3
    digest: sha256:5fb7150eb75339af8259de14ec7438ce6b290bbd6e43425c27dc97263c565e6d
    pullPolicy: IfNotPresent
throttle:
  bucket_period: 60
  bucket_limit: 8000
  reset_rate: 100
  drop_logs: true
volumes:
  - name: varlog
    mountPath: /var/log
    hostPath: /var/log
    readOnly: false
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    hostPath: /var/lib/docker/containers
    readOnly: true
    
# Add to override conf file in docker image
# configFiles:
#   fluent.conf: |-
#     <match **>
#       @type ...
#     </match>
