---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.elasticsearch.host }}"
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: "{{ .Values.elasticsearch.host }}"
  namespace: kube-system
subsets:
{{- $port := .Values.elasticsearch.port -}}
{{- range $ip := .Values.elasticsearch.ip }}
  - addresses:
      - ip: {{ $ip }}
    ports:
      - port: {{ $port }}
{{- end }}
