name: Release Docker image

on:
  push:
    tags:
      - '[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Docker image
      run: |
        make docker IMAGE_TAG=${GITHUB_REF##*/}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image
      run: |
        docker push ghcr.io/nais/nais-logd/nais-logd:${GITHUB_REF##*/}
