name: Release Docker image

on:
  push:
    tags:
      - '[0-9]+'
jobs:
  release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Docker image
      run: |
        make docker IMAGE_TAG=${GITHUB_REF##*/}
    - name: Login GPR
      run: |
        docker login -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN} ghcr.io
    - name: Push Docker image
      run: |
        docker push ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF##*/}
